### ISSUE TITLE
BaseNode not found 

### ISSUE THREAD

**Issue by pourion** [andrewyatesg/tensor-networks-mnist#1]
Hello Andrew,

Thank you for this very nice example of implementing matrix product states for machine learning. I was trying to play around with your code but I realized the BaseNode that you import from tensornetwork.network_components is removed from latest tensornetwork library. Is there a workaround for this issue? Unfortunately I am new to tensornetwork and don't know what would be an equivalent to BaseNode to replace it myself... 
I appreciate your help.

Best,
Pouria

**Comment by andrewyatesg** [comment]
Hi Pouria - Unfortunately, I haven't touched tensornetwork for about a year, so I'm not sure how to fix that. I may come back to this project sometime in the future when I have freetime, in which case I will update it to use the latest tensornetwork version, add new features, fix bugs, etc. Thanks for letting me know!

**Comment by Vaishnavi-Markunde** [comment]
> Hello Andrew,
> 
> Thank you for this very nice example of implementing matrix product states for machine learning. I was trying to play around with your code but I realized the BaseNode that you import from tensornetwork.network_components is removed from latest tensornetwork library. Is there a workaround for this issue? Unfortunately I am new to tensornetwork and don't know what would be an equivalent to BaseNode to replace it myself... I appreciate your help.
> 
> Best, Pouria

Hi @pourion , were you able to solve the issue?
